OnlineCourse/urls.py
"""
Definition of urls for OnlineCourse.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views


import app.forms
import app.views


from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from django.conf.urls.static import static #импорт функций для настройки доступа к загруженным файлам(и две строчки снизу)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^goods/', include('shop.urls',  namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),

    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^addproduct$', app.views.addproduct, name='addproduct'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^my_orders$', app.views.my_orders, name='my_orders'),
    url(r'^users_orders$', app.views.users_orders, name='users_orders'),
    url(r'^search/', include ('search.urls')),                        #Поиск по сайту
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),  #Купон
    

    
    
   

  
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    
    url(r'^$', views.product_list, name='product_list'),
    
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
                                                        
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

#PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='quantity',max_value = 99 ,min_value = 1,   widget=forms.NumberInput())
    #quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

coupons/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    code = forms.CharField()

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
import django

from django.views.decorators.http import require_POST
from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,'category': category,'categories': categories,'coupon_apply_form':coupon_apply_form})

cart/templates/cart/detail.html
{% extends "app/layout.html" %}
{% load static %}

<head>
	<title>Product</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

    </head>


{% block content %}
 
	
		

	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg m-t-75">
			<a href="{% url 'home' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Главная
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Корзина
			</span>
		</div>
	</div>
		

	<!-- Shoping Cart -->
	<div class="bg0 p-t-75 p-b-85">
         
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
					<div class="m-l-25 m-r--38 m-lr-0-xl">
						<div class="wrap-table-shopping-cart">
							<table class="table-shopping-cart">
								<tr class="table_head">
									<th class="column-1">Продукт</th>
									<th class="column-2"></th>
									<th class="column-3">Цена за шт</th>
									<th class="column-4">Кол-во</th>
									<th class="column-5">Итог</th>
                                    <th class="column-6">Удалить</th>
								</tr>
                                {% for item in cart %}
                                    {% with product=item.product %}
								<tr class="table_row">
									<td class="column-1">
										<div class="how-itemcart1">
											<a href="{{ product.get_absolute_url }}">
											<img src="{% if product.image1 %}{{ product.image1.url }}{% else %}{% static 'content/no_image.png' %}{% endif %}">
                                            </a>
										</div>
									</td>
									<td class="column-2">{{ product.name }}</td>
									<td class="column-3">{{ item.price }} руб.</td>
									<td class="column-4">
										{{item.quantity}}
									</td>
									<td class="column-5">{{ item.total_price }} руб.   </td>
                                    <td class="column-6" ><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
								</tr>
                                {% endwith %}
                                {% endfor %}
								
							</table>
						</div>
                        
						<div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
                            <form action="{% url "coupons:apply" %}" method="post">
                             {% csrf_token %}
							<div class="flex-w flex-m m-r-20 m-tb-5">
								<input class="stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5" type="text" required id="id_code" name="code" placeholder="Coupon Code">
									
								<input type="submit" class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5" value="Применить купон">
									
								
							</div>

							
                                </form>
						</div>
                            
					</div>
				</div>
                
				<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
						<h4 class="mtext-109 cl2 p-b-30">
							-----------------------------------------------------
						</h4>

						

						

						<div class="flex-w flex-t p-t-27 p-b-33">
							<div class="size-208">
								<span class="mtext-109 cl2 p-b-30">
									К оплате:
								</span>
							</div>

							<div class="size-209 p-t-1">
								<span class="mtext-109 cl2 p-b-30">
									{{ cart.get_total_price }} руб. 

                                    
								</span>
							</div>
						</div>

                        <h4 class="mtext-109 cl2 p-b-30">
							-----------------------------------------------------
						</h4>

                        {% if cart.coupon %}
                         

                        <div class="flex-w flex-t p-t-27">
							<div class="size-100">
								<span class="mtext-110 cl2 p-b-30">
									Вы применили купон "{{ cart.coupon.code }}" 
								</span>
							</div>

							<div class="size-100 p-t-7">
								<span class="mtext-110 cl2 p-b-30">
									Ваша скидка -{{ cart.coupon.discount }}%  ( {{ cart.get_discount|floatformat:"2" }} руб.) 

                                    
								</span>
							</div>

                           

                            <div class="size-110 p-t-7">
								<span class="mtext-109 cl2 p-b-15">
									К оплате:  {{ cart.get_total_price_after_discount|floatformat:"2" }}

                                    
								</span>
							</div>

						</div>

                         <h4 class="mtext-109 cl2 p-b-30">
							-----------------------------------------------------
						</h4>
                        {% else %}
                        <div class="size-110 p-t-7">
								<span class="mtext-110 cl2 ">
									Вы пока не применили купон.

                                    
								</span>
							</div>

                        
                        {% endif %}
                        
                        {% if cart  %}
						<a href="{% url "orders:order_create" %}" class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
							Продолжить
						</a>
                        {% else %}

                        <a href="{% url "shop:product_list" %}" class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
							Добавьте товар
						</a>

                        {% endif %}
                        
					</div>
				</div>
                
			</div>
		</div>
	</div>




{% endblock %}