OnlineCourse/urls.py
"""
Definition of urls for OnlineCourse.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views


import app.forms
import app.views


from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from django.conf.urls.static import static #импорт функций для настройки доступа к загруженным файлам(и две строчки снизу)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^goods/', include('shop.urls',  namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),

    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^addproduct$', app.views.addproduct, name='addproduct'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^my_orders$', app.views.my_orders, name='my_orders'),
    url(r'^users_orders$', app.views.users_orders, name='users_orders'),
    url(r'^search/', include ('search.urls')),                        #Поиск по сайту
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),  #Купон
    

    
    
   

  
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    
    url(r'^$', views.product_list, name='product_list'),
    
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
                                                        
]

app/models.py
"""
Definition of models.
"""
from django.contrib.contenttypes.fields import GenericRelation

from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from datetime import datetime
from django.core.urlresolvers import reverse
# Create your models here.
# модель данных Блога

class Blog(models.Model):
    title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")
    description = models.TextField(verbose_name = "Краткое содержание")
    content = models.TextField(verbose_name = "Полное содержание" ,)
    posted = models.DateTimeField(default = datetime.now(),db_index = True, verbose_name = "Опубликована")
    author = models.ForeignKey(User, null=True, blank=True, on_delete = models.SET_NULL, verbose_name = "Автор")
    image = models.FileField(default = 'temp.jpg', verbose_name = "Путь к картинке")

   

    def get_absolute_urls(self): #метод возвращает строку с уникальным интернет адресом записи
        return reverse("blogpost", args=[str(self.id)])

    def __str__(self):
        return self.title # метод возвращает название используемое для представления отдельных заголовков
    
    class Meta:
        db_table = "Posts" # имя таблицы для модели
        ordering = ["-posted"] # порядок сортировки данных в модели (- означает по убыванию)
        verbose_name = "статья блога" # имя под окторым модель будет отображаться в админ разделе
        verbose_name_plural = "статьи блога" # тоже для всех статей блога

admin.site.register(Blog)

class Comment(models.Model):
    text = models.TextField(verbose_name = "Комментарий")
    date = models.DateTimeField(default = datetime.now(),db_index = True, verbose_name = "Дата")
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "Автор")
    post = models.ForeignKey(Blog, on_delete = models.CASCADE, verbose_name = "Статья")
   

    def __str__(self):
        return 'Комментарий %s к %s' %(self.author, self.post)

    class Meta:
        db_table = "Comments" # имя таблицы для модели
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии к статьям блога"
        ordering= ["-date"]



class Contact(models.Model):
    email = models.EmailField(max_length = 255 , verbose_name = 'email')
    text = models.CharField(max_length = 1000, verbose_name = 'Вопрос')
    date = models.DateTimeField(default = datetime.now(),db_index = True, verbose_name = "Дата")

    def __str__(self):
       return self.email

    class Meta:
        verbose_name = "Вопрос от пользователя"
        verbose_name_plural = "Вопросы от пользователей"
        ordering = ["-date"]

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92 m-t-80" style="background-image: url('static/app/content/site/images/bg-01.jpg');">
		<h2 class="ltext-105 cl0 txt-center">
			О нас
		</h2>
	</section>	


	<!-- Content page -->
	<section class="bg0 p-t-75 p-b-120">
		<div class="container">
			<div class="row p-b-148">
				<div class="col-md-7 col-lg-8">
					<div class="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
						<h3 class="mtext-111 cl2 p-b-16">
							Кто же мы такие?
						</h3>

						<p class="stext-113 cl6 p-b-26">
							Компания «phone-store» — российская сеть магазинов по продаже смартфонов. 
«Phone-Store» – двухкратный лауреат премии «Права потребителей и качество обслуживания».

В 2010 году компания «Эльдорадо» была удостоена ряда отраслевых наград, таких как EMEA Channel Academy: «Ритейлер года в регионе РФ & СНГ»; премии в номинации «Лучшие цены», организованной экспертным проектом Hi-Tech.Mail.Ru, а также Online Retail Russia Awards в номинации «Лучший интернет-магазин» (2010, 2019), обладатель премии Russian Retail Awards 2016, двукратный обладатель премии EMEA Channel Academy: «Ритейлер года в регионе РФ & СНГ» (2015, 2016), а также обладатель приза зрительских симпатий конкурса АКМР «Лучшее корпоративное видео 2016».

На данный момент количество успешный продаж «Phone-Store» составляет более 250 000 единиц товара.

Стратегическое партнерство с ведущими международными производителями позволяет клиентам «Phone-Store» в числе первых узнавать о впечатляющих инновациях и получать эксклюзивные новинки.


						</p>

						

						<p class="stext-113 cl6 p-b-26">
							Остались вопросы? Звоните по телефону +7 900 9902336 или пишие на почту <a href="#">phone-store.gmail.com</a>
						</p>
					</div>
				</div>

				<div class="col-11 col-md-5 col-lg-4 m-lr-auto">
					<div class="how-bor1 ">
						<div class="hov-img0">
							<img src="{% static 'app/content/site/images/about-01.jpg' %}" alt="IMG">
						</div>
					</div>
				</div>
			</div>
			
			
		</div>
	</section>	
	
		

	
	


	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>



		
		
{% endblock %}

app/templates/app/add_product.html
<!DOCTYPE html>
{% extends "app/layout.html" %}
{% load static %}

   
    
    {% block content %}
    <div class=" add_product">
    <form enctype="multipart/form-data" method="POST" ">
        {% csrf_token %}
        {{add_product.as_p}}
        <br />
        <button type="submit" class="btn btn-primary m-b-75"> Добавить </button>
    </form>
</div>
    {% endblock %}

app/templates/app/anketa.html
{% extends "app/layout.html" %}

<div class="container body-content">


      
{% block content %}
{% if form != None %}
<br><h2> Отправьте пожалуйста заполненную анкету </h2></br>
    <div>
        <form method ="POST">
        {% csrf_token %}
        <label for=" {{ form.name.id_for_label}}" > {{form.name.label}}:</label>
        {{form.name}} <br><br>
        <label for="{{form.city.id_for_label}}">{{form.city.label}}:</label>
        {{form.city}}<br><br>
         <label for=" {{form.gender.id_for_label}}">{{form.gender.label}}:</label>
        {{form.gender}}<br><br>
        <label for=" {{form.job.id_for_label}}">{{form.job.label}}:</label>
        {{form.job}}<br><br>
        <label for=" {{form.internet.id_for_label}}">{{form.internet.label}}:</label>
        {{form.internet}}<br><br>
        <label for=" {{form.notice.id_for_label}}">{{form.notice.label}}:</label>
        {{form.notice}}<br><br>
        <label for=" {{form.email.id_for_label}}">{{form.email.label}}:</label>
        {{form.email}}<br><br>
        <label for=" {{form.message.id_for_label}}"><br><br><br><br><br>{{form.message.label}}:</label>
        {{form.message}}<br><br>
        <input type="submit" value="Отправить">
        </form>
    </div>
{% else %}
<br><h2>Благодарим за отправленную форму</h2>
    <h3>Вы рассказали нам о себе следующее:</h3>
<ul>
    <li><span>Имя:</span>{{data.name}}</li>
    <li><span>Город:</span>{{data.city}}</li>
    <li><span>Пол:</span>{{data.gender}}</li>
    <li><span>Работа:</span>{{data.job}}</li>
    <li><span>В интернете:</span>{{data.internet}}</li>
    <li><span>Получать новости с сайта на e-mail:</span>{{data.notice}}</li>
    <li><span>Ваш e-mail:</span>{{data.email}}</li>
    <li><span>Информация о себе:</span>{{data.message}}</li>
</ul>
    </div>
{% endif %}
{% endblock %}


        


</body>
</html>

app/templates/app/blog.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}
<body>
<section class="bg-img1 txt-center p-lr-15 p-tb-92 m-t-80" style="background-image: url('static/app/content/site/images/bg-02.jpg');">
		<h2 class="ltext-105 cl0 txt-center">
			Новости
		</h2>
</section>	


	<!-- Content page -->
	<section class="bg0 p-t-62 p-b-60">
       
		<div class="container">
			<div class="row">
                
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
                        
						<!-- item blog -->
						<div class="p-b-63">
                           {% for post in posts %} 
							<a href="{% url 'blogpost'  parametr=post.id %}" class="hov-img0 how-pos5-parent ">
							 	
                               
                                <img class="hov-img0 how-pos5-parent" src="{{post.image.url}}" alt="Картинка"  />
                                
								<div class="flex-col-c-m size-123 bg9 how-pos5">
									<span class="ltext-107 cl2 txt-center">
										
									</span>

									<span class="stext-109 cl3 txt-center">
										
									</span>
								</div>
							</a>
                            
							<div class="p-t-32">
                                
                                
								
									<p class="ltext-108 cl2 hov-cl1 trans-04">
										{{post.title}}
									
								

								<p class="stext-117 cl6">
									{{post.description}}
								</p>
                                
								<div class="flex-w flex-sb-m  m-b-35"> <!--Тут я задал расстояние между картинками статьи блога m-b-50  (margin-bottom) и убрал p-t-18-->
                                    
									<span class="flex-w flex-m stext-111 cl2 p-r-30 m-tb-10">
										<span>
											<span class="cl4">By</span> {{post.author}} 
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>
                                        

										<span>
											{{post.posted}}  
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>

										<span>
											{{ post.comment_set.count }} Комментариев
										</span>
									</span>

									<a href="{% url 'blogpost'  parametr=post.id %}" class="stext-101 cl2 hov-cl1 trans-04 m-tb-10">
                                        Читать далее
								       <i class="fa fa-long-arrow-right m-l-9"></i>
									</a>
								</div>
                                    {% endfor %}
							</div>
						</div>

						</div>
					</div>
				</div>
			</div>
        </section>	

    {% endblock %}






</body>

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% load staticfiles %}
{% block content %}





<body>

<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg m-t-75">
			<a href="{% url 'home' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Главная
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<a href="{% url 'blog' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Блог
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				{{post_1.title}}
			</span>
		</div>
	</div>


	<!-- Content page -->
	<section class="bg0 p-t-52 p-b-20">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
						<!--  -->
						<div class="wrap-pic-w how-pos5-parent">
							{% if post_1.image and post_1.image.url != "/media/temp.jpg" %}
                            <img src="{{post_1.image.url}}" alt="Картинка"  />
                            {% endif %}
    
							
						</div>

						<div class="p-t-32">
                            
							<span class="flex-w flex-m stext-111 cl2 p-b-19">
								<span>
									<span class="cl4">By</span> {{post_1.author}}  
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>

								<span>
									{{post_1.posted}}
									
								</span>

							</span>

							<h4 class="ltext-109 cl2 p-b-28">
								{{post_1.title}}
							</h4>

							<p class="stext-117 cl6 p-b-26">
								{% autoescape off %}
                            <p> {{ post_1.content|linebreaksbr }} </p>
                            {% endautoescape %}
						

							
                            
						</div>

						
						<!--  -->
                        
						<div class="p-t-40">
                            {% if user.is_authenticated %}
							<h5 class="mtext-113 cl2 p-b-12">
								Оставить комментарий
							</h5>

                            

							

							<form method="POST" >
                                {% csrf_token %}
								<div class="bor19 m-b-20">
									<textarea class="stext-111 cl2 plh3 size-124 p-lr-18 p-tb-15" name="text" placeholder="Комментарий..." required id="id_text"></textarea>
								</div>
								<button type="submit" class="flex-c-m stext-101 cl0 size-125 bg3 bor2 hov-btn3 p-lr-15 trans-04">
									Отправить
								</button>
                                </form>
                            {% else %}
                            <p class="stext-107 cl6 p-b-40">
								Для добавления комментария авторизуйтесь.
							</p>
                            {% endif %}


						</div>
                        <div class="blogpost_comment">
                        {% for comment in comments %}

                <h1>{{comment.author}}</h1>
                <h2>{{comment.text|linebreaksbr}}</h2>
                <h3>{{comment.date}}</h3>
                     
                {% endfor %}
                <p><a href="{% url 'blog' %}">Назад</a></p>
					</div>
				</div>
                </div>

                
				
		    </div>
		</div>
				
	</section>	


{% endblock %}
</body>

app/templates/app/index.html
{% extends 'app/layout.html' %}

{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">

<head>
	<title>Главная</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    
</head>
{% block content %}
<body class="animsition">
	
	

		

	<!-- Slider -->
	<section class="section-slide">
		<div class="wrap-slick1">
			<div class="slick1">
                    
				<div class="item-slick1"  style="background-image: url(static/app/content/banner1.jpg);"> 
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									Samsung
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									GALAXY S20 fe
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
								<a href="{% url 'shop:product_list' %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Посмотреть
								</a>
							</div>
                            
						</div>
					</div>
				</div>

				<div class="item-slick1" style="background-image: url(static/app/content/banner2.jpg);">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1_2 animated visible-false" data-appear="rollIn" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									Посмотреть
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="lightSpeedIn" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									Redmi Note 10
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="slideInUp" data-delay="1600">
								<a href="{% url 'shop:product_list' %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Посмотреть
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="item-slick1" style="background-image: url(static/app/content/banner3.jpg);" >
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="rotateInDownLeft" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									Apple
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="rotateInUpRight" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									iPhone 12
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="rotateIn" data-delay="1600">
								<a href="{% url 'shop:product_list' %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Посмотреть
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

    


    <!------------------------------------------------------------------- НАШИ БРЕНДЫ---------------------------------------------------------->

 <section class="sec-product bg0 p-t-100 p-b-50">
		<div class="container">
			<div class="p-b-32">
				<h3 class="ltext-105 cl5 txt-center respon1">
					Бренды в нашем магазине
				</h3>
			</div>

			<!-- Tab01 -->
			<div class="tab01">
				

				<!-- Tab panes -->
				<div class="tab-content p-t-50">
					<!-- - -->
					<div class="tab-pane fade show active" id="best-seller" role="tabpanel">
						<!-- Slide2 -->
						<div class="wrap-slick2">
							<div class="slick2">
								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/samsung.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/xiaomi.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/apple.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/huawei.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/samsung.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/huawei.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/apple.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>

								<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
									<!-- Block2 -->
									<div class="block2">
										<div class="block2-pic hov-img0">
											<img src="{% static 'app/content/brands/xiaomi.png' %}" alt="IMG-PRODUCT">

											
										</div>

										
									</div>
								</div>
							</div>
						</div>
					</div>
                    </div>
                </div>
            </div>
        </section>



    <section class="sec-blog bg0 p-t-60 p-b-90">
		<div class="container">
			<div class="p-b-66">
				<h3 class="ltext-105 cl5 txt-center respon1">
					Последние новости
				</h3>
			</div>
             
			<div class="row">
                {% for post in posts_index %}
				<div class="col-sm-6 col-md-4 p-b-40">
					<div class="blog-item">
						<div class="hov-img0">
							<a href="{% url 'blogpost'  parametr=post.id %}">
								<img class="hov-img0 how-pos5-parent" src="{{post.image.url}}" alt="Картинка"  />
							</a>
						</div>

						<div class="p-t-15">
							<div class="stext-107 flex-w p-b-14">
								<span class="m-r-3">
									<span class="cl4">
										Автор:  
									</span>

									<span class="cl5">
										{{post.author}}
									</span>
								</span>

								<span>
									<span class="cl4">
										Дата:  
									</span>

									<span class="cl5">
										{{post.posted}}   
									</span>
								</span>
							</div>

							<h4 class="p-b-12">
								<a href="blog-detail.html" class="mtext-101 cl2 hov-cl1 trans-04">
									{{post.title}}
								</a>
							</h4>

							<p class="stext-108 cl6">
								{{post.description}}
							</p>
						</div>
					</div>
				</div>

				{% endfor %}
						</div>
            
					</div>
				
			
		
	</section>

    
<!--==================================================================================================================================================-->
   




</body>
{% endblock %}
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}
    
{% block content %}{% load staticfiles %}
       

      <div class="images">
          <div class="client1">
      <a href ="https://magnit.ru/" target="_blank"> <img src="{% static 'app/content/magnit.png' %}" alt="Logo 1"/></a>
          <p>«Магнит» является одной из ведущих розничных сетей в России по торговле продуктами питания, лидером по количеству магазинов и географии их расположения.</p></div>
      <div class="client2">
          <a href ="https://www.vostbank.ru/" target="_blank"> <img src="{% static 'app/content/vostok.png' %}" alt="Logo 2"/></a>
          <p>Банк «Восточный» — универсальный банк федерального значения. Специализируется на розничном кредитовании и предлагает полный комплекс услуг для предпринимателей. 
          Располагает широкой сетью продаж, преимущественно на Дальнем Востоке и в Восточной Сибири.</p></div>
      <div class="client3">
          <a href ="https://www.vostbank.ru/" target="_blank"> <img src="{% static 'app/content/lenta.png' %}" alt="Logo 3"/></a>
          <p>«Ле́нта» — российская сеть гипермаркетов. Управляется компанией «Lenta Ltd». Головной офис находится в Санкт-Петербурге.</p></div>
      </div>

      
   
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}


<div class="login_form">
    <h2>{{ title }}</h2>
<div class="row">
    
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте созданный аккаунт для входа.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Введите корректный логин или пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
   
</div>
</div>
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/my_orders.html
{%  extends 'app/layout.html' %}


{% block content %} 
<div class="container">
     <div class="table_detail_myorders">
        
         <table class="table-bordered">
              <tr>
      <td colspan="2">Вы заказывали товар</td>
            
             
      <td colspan="2">На сумму</td>
             
      <td colspan="2">Дата заказа</td>
             </tr>
         {% for order in orders %}
         {% for item in order_item %}
    
    
      
    <tr>
        <td colspan="2"><b>{{item.product}}</b></td>
         <td colspan="2"><b>{{item.price}}</b></td>
       <td colspan="2"><b>{{order.created}}</b></td>
      
    </tr>
            
        {% endfor %}
         {% endfor %}

    </table>
        
         </div>
    </div>









{% endblock %}